### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/infografia-salathiel1999-1#1]
[Infografia -.pdf](https://github.com/SistemasTecTlaxiaco/infografia-salathiel1999-1/files/8159459/Infografia.-.pdf)

**Comment by Rosa218** [comment]
Calificación :20
Calificó Rosa Salazar Doroteo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
